[toolchain]
anchor_version = "0.31.0"
solana_version = "2.2.1"

[features]
resolution = true
skip-lint = false

[programs.devnet]
claims_processor = "4tiYerbWqYX6tiDscXiMG3kTpXkBgrd2bLor8Ne49uzA"
dao_governance = "C26MZeStsmBkom4QzegKXXuyhHLto1kajLjmpBZBYru5"
escrow_program = "8HZPdcQXc42SAk94nVksQaBF1ddKtiGr46vwbHmMmwex"
freelance_insurance = "81APCGsWxDgfwsvjLgt1CqSqvMXpkTTseuYdeQ2ebWEP"
insurance_program = "HpkxHodkn839YUPUYqpyjjC2mMcPp49SF73XSBJeodKy"
risk_pool_program = "U5GxZ56nPBCT2REu4LUfytu51ZVtXAKhaThYFNbK6HJ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "./devnet-deploy.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
