[toolchain]
anchor_version = "0.31.0"
solana_version = "1.15.2"

[features]
resolution = true
skip-lint = false

[programs.devnet]
claims_processor = "5pQBQ2oz7RWJVrcjVzCocbzZsqcAPokwn4Fs3UtPEtda"
dao_governance = "FDJJ1NSYbLe3v1wCVGXcrA1hqKvf2BbpbNXE3G6TSuf7"
enhanced_claims = "BYE7dnHiF7ptZY1oAxcRBA13NVKsCiFQ2QBQQEAnSf8H"
enhanced_cover = "8wb2a2qR2rEpqALC8a1TdnGgsbVJLFUeRJQ5y7EfvQRT"
escrow_program = "FUnA7YXC27uJBqrcS2Q5ofGL4ghyxoBZkieCtpxvCVab"
freelance_insurance = "5PE9juxGEzx4gMhYBrpeypj8jYdiqNHvnK7PNZ3GAUvW"
insurance_program = "Ge2xB8Hk3GY1p3YNJWbaxqNNRB6f18VxMsrjfSJ1DPVg"
policy_nft = "2pwwsiBvc21ZcBaVmdWcymvz3QiP8DuYkB97S7gNoK6T"
reputation_program = "9KbeVQ7mhcYSDUnQ9jcVpEeQx7uu1xJfqvKrQsfpaqEq"
risk_pool_program = "FroU966kfvu5RAQxhLfb4mhFdDjY6JewEf41ZfYR3xhm"
staking_program = "z1VyDVFdUGUXQzx6Dikrzt7aDR8BLgSARcncUvymcDb"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "./devnet-deploy.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
