[toolchain]
anchor_version = "0.28.0"

[features]
resolution = true
skip-lint = false

[programs.devnet]
claims_processor = "B5zguYu7xMS2DApHWLEe2Er4NA1yTE66buNxvT91wq7B"
dao_governance = "2JNR5WSbjKoDuKidQyhVJtGzEtNGdYB1a8YnVkDXivWW"
escrow_program = "5yWSCq9kvXTeB2JAKSZu7mPPoR7Nw5nFQotVU9ApfsCz"
insurance_program = "37dpkWEmajidF7PKS9v43m2QfTxo7kxxYaEQcAh5c9uD"
risk_pool_program = "GywN3pRCKVXyAVNxkePotBFEYcFSvULw5qefacsUmsdt"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "./devnet-deploy.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
