[toolchain]
anchor_version = "0.31.0"
solana_version = "2.2.1"

[features]
resolution = true
skip-lint = false

[programs.devnet]
claims_processor = "64pxnRW6T4UKRdBtZbRR6DwcWXzS5ahVYHVhcHZk44xo"
dao_governance = "6u997rgZTjwj3obHzr2fP9gzNSkrkvMZDYa4VFCDNw5c"
escrow_program = "KpH6xpxhNSh88AxBTgTUQ9KgvM2cKLcVrzA6Ke7QyK5"
freelance_insurance = "4gjEkiunXY7aLHASi49PGv3VfhKVPKv1fUWEdQTQXUiN"
insurance_program = "DKmNWT36RZTkN1ggdLUvze1JvB3RFZ4HHYGh6zLK3rbc"
risk_pool_program = "BXkKs3SXcjQiyfrEWx6QXWpfbkhpa6gwEG2PkekyaAdz"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "./devnet-deploy.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
