[toolchain]
anchor_version = "0.31.0"
solana_version = "1.16.0"

[features]
resolution = true
skip-lint = false

[programs.devnet]
claims_processor = "GRySeLQy7do9nMfJWbH9YmBRS1MHGF79AnmAHKFiJRaN"
core = "BWop9ejaeHDK9ktZivqzqwgZMN8kituGYM7cKqrpNiaE"
dao_governance = "48r3FuT5gr4wrfr2qr4sP8yEggyXCqML6CmyB8t3EnEA"
enhanced_claims = "7sNGFjKYPUK1fgguDsbN96R6m6BZJs11KPFSYq3KGBXX"
enhanced_cover = "5y4aVEFhEznVoZo1VNfM13CYKZcFmT8Z97N4UXHpaJGj"
escrow_program = "HbRjXVmWEkbjCejgGLaPsWpECgwoHhXVH1gV5NUzGVSH"
freelance_insurance = "HuZwzjsdGdDUuvAf3GV59FASxx5V2gHRckhFsWcksECd"
insurance_program = "BcZfN4TJYzWZsNXpLFjgEiZSqV124W2uJPEgFHdsp9TD"
policy_nft = "6tcTn7aHDLRmy1u1aQ7WiLJJmfzz9BSUHRmo2Zj5Eyi9"
reputation_program = "ErqSUDAvmuZicGV9zBBAV9eSUo6sJoj7zjuWgASJQxD9"
risk_pool_program = "2nxmHdqSuwVoyae1PpKRgJrKPTVPy59crNJZnqXNbVL2"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "./deploy-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
