[toolchain]
anchor_version = "0.31.0"
solana_version = "2.1.0"

[features]
resolution = true
skip-lint = false

[programs.devnet]
claims_processor = "3NSs6fEa1nJzDMJgEYVtXUc7mA1WNA5C3Wst17WTrEyB"
dao_governance = "CMxCJYTYhk7gczJTHeuPv9z8TctstsXCNuciweDnviCf"
enhanced_claims = "2BQh46xqDMFKSgBXxSTkq8whbv42idXsarGTTwnbafVb"
enhanced_cover = "EV696qnLoxsLwDTKvpJqvz1UcSezez3dHFAiUyTkA7Cq"
escrow_program = "BJdNWSKVWBZDz4Me8Y8hZ3Zhy1sVj3f5pQeowfcear8E"
freelance_insurance = "FhUteMD3L7eZGgLH2SiTzrePzxazTTTrZ8nNFPTVUcVt"
insurance_program = "8sWfHQUJuSsbf3aFW8TWqGXqmnjfpbqrrF6GhnsNAaJu"
policy_nft = "6gq7GB6YHowQ9xdWJtzyi3VCwFx78Ufv29D64ZckTzAu"
reputation_program = "62pv98Ymg4E4WpvZqrxtGA5kHSGwX3VxmKqsSjARAMhc"
risk_pool_program = "4UFr2kyHQmr8efafSRDMT8NL3jsq8tPcx9qFEir3YFVH"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "./devnet-deploy.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
