[toolchain]
anchor_version = "0.31.0"
solana_version = "2.1.0"

[features]
resolution = true
skip-lint = false

[programs.devnet]
claims_processor = "DT8eJ6wc6ZfT3MjDRvqZ8AonSsG3uuviLF8LmMJsievH"
dao_governance = "CNA4hWFgYAwKLgeZRP4EvBc5G2PVQWoDbXtVd5YheBwF"
enhanced_claims = "4jnnT3KKDFbWEci229ku4CGeRaiQupYDKxqDjAaQjyWM"
enhanced_cover = "9TsZshBaMxUnCHeSfvqAZQdKKXWWXQ6sd4Z6S4YvGcxv"
escrow_program = "8icbcJYrXk1yQTbW9C7WKyRGnTFZt3aD8d4kAzDkr5b7"
freelance_insurance = "GpcM7kmhKWE4QKG1AWquX8xTs8mqSWn5r3SqMzTDWsys"
insurance_program = "3GiieAndgnB7Wr3ZRHsvUw2KmFewydo59Py47wKJG4xQ"
policy_nft = "94mWhnLu8RzEbFTE3ftcebd9xQtEG4JPt2y7fwHwcbup"
reputation_program = "CvWfNXEGVivX8sYVjtrFyesav1SaHLFs349QKD12HeKK"
risk_pool_program = "FCNXdEAFDuGJ1vaJDPNMff19qJmSTZi2cRZZjQVh18kM"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "./devnet-deploy.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
