[workspace]
members = [
    "programs/claims-processor",
    "programs/escrow-program",
    "programs/insurance-program",
    "programs/reputation-program",
    "programs/risk-pool-program",
    "programs/staking-program",
    "programs/freelance-insurance",
    "programs/core",
    "programs/enhanced-cover",
    "programs/enhanced-risk-pool",
    "programs/policy-nft",
    "programs/dao-governance"
]
resolver = "2"

[profile.release]
overflow-checks = true
lto = "fat"
codegen-units = 1
panic = "abort"

[profile.release.build-override]
opt-level = 3
incremental = false
codegen-units = 1

[profile.dev]
split-debuginfo = "unpacked"
opt-level = 0

[profile.test]
opt-level = 3

[workspace.metadata.solana]
sdk-version = "2.1.0"

# Using Anchor 0.31.0 - matching the installed version
# This ensures all programs use identical dependency versions
[workspace.dependencies]
anchor-lang = { version = "0.31.0", features = ["init-if-needed"] }
anchor-spl = { version = "0.31.0", default-features = false }
solana-program = "2.1.0" 
borsh = "0.10.3"
borsh-derive = "0.10.3"
spl-token = "4.0.0"
spl-associated-token-account = "1.1.3"
mpl-token-metadata = { version = "1.11.1", features = ["no-entrypoint"] }  
thiserror = "1.0.40"
zeroize = "1.3.0"

# Add patches to resolve dependency conflicts
[patch.crates-io]
# Fix borsh serialization issues for mpl-token-metadata
borsh = "0.10.3"
borsh-derive = "0.10.3"
# Force solana-zk-sdk to use solana-program 2.1.0
solana-zk-sdk = { git = "https://github.com/solana-labs/solana", tag = "v2.1.0" }
# Ensure consistent solana-program version
solana-program = { git = "https://github.com/solana-labs/solana", tag = "v2.1.0" }
