[package]
name = "freelance-shield-simple-core"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-program = "1.16.0"
borsh = "=0.10.3"
thiserror = "1.0.66"

[lib]
crate-type = ["cdylib", "lib"]
