[build]
rustflags = ["-C", "target-cpu=native"]

[net]
git-fetch-with-cli = true


# Add specific Solana BPF settings
[unstable]
build-std = ["std", "panic_abort"]

[alias]
sbf-build-deps = "build-bpf --manifest-path=Cargo.toml"

# Add dependency overrides to resolve conflicts
[dependencies.override]
subtle = "2.4.1"